// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://febyxtdegaaeoaibzlme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlYnl4dGRlZ2FhZW9haWJ6bG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzkzNzYsImV4cCI6MjA2MDk1NTM3Nn0.bD7XjVEld3FG7uqlPU3I2RZvdzBI3wqG3tXMHLYOwiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);